### ISSUE TITLE
Configuration improvements

### ISSUE THREAD

**Issue by squeed** [openshift/cluster-network-operator#46]
Some configuration improvements we should do before 1.0:

- Get rid of the backwards bit for host subnet length
- Make ServiceNetwork an array
- Fix all the capitalization - if @danwinship hasn't found it yet :-)
- Explicit Multus mode?

**Comment by squeed** [comment]
@danwinship I suspect you have more thoughts about this.

**Comment by squeed** [comment]
Another: rename "ClusterNetworks" to "ClusterNetwork" to match the cluster API object.

**Comment by pecameron** [comment]
@squeed Are we still doing ip/netmask/submask format in ovn on 4.0? So we maintain the old format on SDN and the new on OVN?

**Comment by squeed** [comment]
@pecameron we'll use a single type here and convert it internally based on the network provider.

**Comment by danwinship** [comment]
I'd like to get https://jira.coreos.com/browse/SDN-198 in too. So something like, we deprecate `Mode` and replace it with `Isolation`, with values:
- `None` - All traffic is allowed by default. Project admin can create NetworkPolicies to isolate-and-then-partially-unisolate some pods. (k8s default behavior)
- `Full` - All traffic is denied by default. Project admin must create NetworkPolicies to unisolate pods. (k8s default but with "deny" rather than "accept" as the fallback rule)
- `Namespace` - Traffic is allowed within the namespace and denied between namespaces. Project admin can delete the default policy to fully isolate the namespace, or create additional policies to unisolate between namespaces.

The default would probably be `Namespace`. (In the future, `ovs-subnet` users would be migrated to `isolation: None`, `ovs-multitenant` users would be migrated to `isolation: Namespace`, and `ovs-networkpolicy` users would have to choose.)

**Comment by danwinship** [comment]
@squeed any reason to keep this open?

**Comment by squeed** [comment]
Nope, we did most of those things. Thanks for doing a sweep.
