### ISSUE TITLE
ca bundle injection as jks

### ISSUE THREAD

**Issue by mathianasj** [openshift/cluster-network-operator#700]
Have the ability to inject the ca trust bundle as a jks file for java consumption in addition to just pem files

**Comment by sanbornick** [comment]
Not with that attitude

**Comment by sanbornick** [comment]
We'd like to see all 3 outputs that ca-certificates produces for parity with a full blown os. Without this, we have to maintain a build pipeline that gets explicit images from outside sources and imperatively add the anchors and run the update command in a docker build for those images to work in a private pki world.

If this had parity with ca-certificates, we can declaratively inject PKI into any image from _any source_, _at runtime_. I can not stress how much time this would save, and how much stuff we could get rid of.

**Comment by seanmalloy** [comment]
@damemi and @ingvagabund would it be possible to reopen this? Asking for a friend. :-)

**Comment by sanbornick** [comment]
Thank you @ingvagabund

**Comment by sanbornick** [comment]
Another consideration would be to also add the openshift signer ca that is presented at `/var/run/secrets/kubernetes.io/serviceaccount` so that app developers can point at a single bundle and know that it will work for intracluster communication as well as external communication on a private network, instead of having to change bundle based on the target.

**Comment by cpmoore** [comment]
I was coming here to ask for the exact same thing, guess you beat me to the punch.
